version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5001:5000"
#    scores-service:
#      build: .
#      image: EranShimon/worldofgame:latest
#      ports:
#        - "8777:8777"

    volumes:
      - ./MainScores.py:/app/MainScores.py
      - ./Scores.txt:/app/Scores.txt
    environment:
      - FLASK_APP=MainScores.py
    command: flask run --host=0.0.0.0